### ISSUE TITLE
Generating new application with flask-server template fails

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/cloud-harness#558]
Running:
```
harness-application clockdate -t flask-server
```
with latest [develop](https://github.com/MetaCell/cloud-harness/commit/27ae0fe447ba16b9f31a43269cfb3d5076ab16ff)

returns:
```
WARNING:root:Overwriting file applications/clockdate/api/config.json with /home/afonso/Projects/MetaCell/cloud-harness/tools/cloudharness_utilities/application-templates/base/api/config.json
INFO:root:Merged/overridden file content of applications/clockdate/api/openapi.yaml with /home/afonso/Projects/MetaCell/cloud-harness/tools/cloudharness_utilities/application-templates/base/api/openapi.yaml
WARNING:root:Overwriting file applications/clockdate/test/api/test_st.py with /home/afonso/Projects/MetaCell/cloud-harness/tools/cloudharness_utilities/application-templates/base/test/api/test_st.py
WARNING:root:Overwriting file applications/clockdate/test/e2e/landing.spec.ts with /home/afonso/Projects/MetaCell/cloud-harness/tools/cloudharness_utilities/application-templates/base/test/e2e/landing.spec.ts
INFO:root:Merged/overridden file content of applications/clockdate/deploy/values.yaml with /home/afonso/Projects/MetaCell/cloud-harness/tools/cloudharness_utilities/application-templates/base/deploy/values.yaml
Traceback (most recent call last):
  File "/home/afonso/.pyenv/versions/ch/bin/harness-application", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/afonso/Projects/MetaCell/cloud-harness/tools/harness-application", line 73, in <module>
    generate_server(app_path)
TypeError: generate_server() missing 1 required positional argument: 'overrides_folder'
```

Expected:
- Generate the application stubs

**Comment by afonsobspinto** [comment]
Some more relevant notes:
The problem seems to happen here: https://github.com/MetaCell/cloud-harness/blob/develop/tools/harness-application#L73
And 'overrides_folder' was added on https://github.com/MetaCell/cloud-harness/pull/515

**Comment by aranega** [comment]
Regarding the generation without failure using `server`, there is a special case for it here: https://github.com/MetaCell/cloud-harness/blob/develop/tools/harness-application#L62-L66

**Comment by filippomc** [comment]
I think we should improve the way templates are used. The double template idea seems confusing to me in general. What are the combinations which are allowed and what not?
I would go for a simpler proposal where only one template can be used by the user, leaving the possibility for the developer to compose the application with multiple templates that are implicitly included. cc @zsinnema

**Comment by zsinnema** [comment]
may be cookiecutter can be of any help https://github.com/cookiecutter/cookiecutter

imo we should not combine templates and go for application types, e.g. Django microservice, Flask microservice, React micorservice etc

**Comment by aranega** [comment]
Feature models are really good to capture configuration options: what are the "features" that are required, their mandatory dependencies, the optional ones as well as the forbidden ones. You can validate them usually to check if there is some "dead" feaure

**Comment by filippomc** [comment]
I'm afraid that the complexity start exploding really soon as we are in the O(n!) and we need to control the allowed ones. I like @zsinnema idea to base the templating on an established library/tool
